
FROM postgres:latest

# PostgreSQL Environment Variables
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=mydb

# Time Zone
ENV TZ=Asia/Tokyo

# Language
# ENV LANG ja_JP.UTF-8
# ENV LANGUAGE ja_JP:ja
# ENV LC_ALL ja_JP.UTF-8


# CMD ["postgres"]
# docker build -t dev/postgres -f Dockerfile.Postgre .
# docker run -d -p 55432:5432 --name postgres-container dev/postgres
