SET MARKUP CSV ON

SET MARKUP CSV ON QUOTE OFF

SET MARKUP CSV ON DELIMITER '|' QUOTE OFF

CREATE TABLE STABLE (
    SELDDATE DATE,
    REG VARCHAR2(20),
    COST NUMBER
) PARTITION BY RANGE (
    SELDDATE
) SUBPARTITION BY LIST (
    REG
) (
    PARTITION P2009Q1 VALUES LESS THAN(TO_DATE('2009-04-01', 'YYYY-MM-DD')) ( SUBPARTITION P2009Q1_KANTO VALUES ('kanagawa', 'Tokyo'), SUBPARTITION P2009Q1_KANSAI VALUES ('Osaka', 'kyoto') ),
    PARTITION P2009Q2 VALUES LESS THAN(TO_DATE('2009-07-01', 'YYYY-MM-DD')) ( SUBPARTITION P2009Q2_KANTO VALUES ('kanagawa', 'Tokyo'), SUBPARTITION P2009Q2_KANSAI VALUES ('Osaka', 'kyoto') )
);

ALTER TABLE STABLE ADD PARTITION P202104 VALUES LESS THAN (TO_DATE('2021/4/01', 'YYYY/MM/DD'));

ALTER TABLE STABLE ADD PARTITION P202104 VALUES LESS THAN (TO_DATE('2021/4/01', 'YYYY/MM/DD')) (SUBPARTITION P2021Q2_KANTO VALUES ('kanagawa', 'Tokyo'));

ALTER TABLE STABLE MODIFY PARTITION P202104 ADD SUBPARTITION P2021Q2_KANSAI VALUES ('Osaka', 'kyoto');

INSERT INTO STABLE (
    SELDDATE,
    REG,
    COST
) VALUES (
    TO_DATE('2020/01/1', 'YYYY/MM/DD'),
    'kanagawa',
    100
);

INSERT INTO STABLE (
    SELDDATE,
    REG,
    COST
) VALUES (
    TO_DATE('2020/02/1', 'YYYY/MM/DD'),
    'Tokyo',
    200
);

INSERT INTO STABLE (
    SELDDATE,
    REG,
    COST
) VALUES (
    TO_DATE('2020/03/1', 'YYYY/MM/DD'),
    'kyoto',
    300
);

SELECT
    TABLE_OWNER --表の所有者
,
    TABLE_NAME --表の名前
,
    COMPOSITE --コンポジット・パーティションかどうか
,
    PARTITION_NAME --パーティション名
,
    HIGH_VALUE --境界値
,
    PARTITION_POSITION --パーティションの位置
,
    COMPRESSION --圧縮設定
,
    NUM_ROWS --データ件数
FROM
    ALL_TAB_PARTITIONS
WHERE
    TABLE_OWNER = 'ORACLE'
ORDER BY
    TABLE_NAME;

SELECT
    TABLE_OWNER --表の所有者
,
    TABLE_NAME --表の名前
,
    PARTITION_NAME --パーティション名
,
    SUBPARTITION_NAME -- サブパーティション名
,
    NUM_ROWS --データ件数
FROM
    DBA_TAB_SUBPARTITIONS
WHERE
    TABLE_OWNER = 'ORACLE'
ORDER BY
    TABLE_NAME;

SELECT
    TABLE_NAME,
    PARTITION_NAME,
    SUBPARTITION_NAME,
    NUM_ROWS
FROM
    USER_TAB_SUBPARTITIONS
ORDER BY
    TABLE_NAME,
    PARTITION_NAME,
    SUBPARTITION_NAME;