version: '3'

volumes:
    db_data:
      name: "wordpress-db-data"
    themes:
      name: "themes"
    plugins:
      name: "plugins"

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
       - db
    image: wordpress:latest
    restart: always
    ports:
      - "58000:80"
      - "58443:443"
    volumes:
      - themes:/var/www/html/wp-content/themes
      - plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
