# docker-compose -f docker-compose.redmine.yml up -d

version: "3"

volumes:
  redmine-plugins:
    name: redmine-plugins
  redmine-themes:
    name: redmine-themes
  redmine-db:
    name: redmine-db

networks:
  redmine-network:
    name: redmine-network

services:
  # redmine 本体
  redmine:
    container_name: redmine
    image: redmine
    restart: always
    ports: # Redmine公開port
      - 8081:3000
    environment:
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_PASSWORD: redminepass
    # Volumeを追加したかったら以下を適当に、、
    volumes:
      - redmine-plugins:/usr/src/redmine/plugins
      - redmine-themes:/usr/src/redmine/public/themes
    networks:
      - redmine-network

  redmine-db:
    image: mysql:5.7
    container_name: redmine-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: redminepass
      MYSQL_DATABASE: redmine
    volumes:
      - redmine-db:/var/lib/mysql
    networks:
      - redmine-network
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci   

