version: "3.1"

volumes:
  mongodb_data1:
    name: mongodb

networks:
  mongo-network:
    name: mongo-network
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.28.11.0/24
         gateway: 172.28.11.1

services:
  mongo:
    image: mongo
    networks:
      mongo-network:
        ipv4_address: 172.28.11.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data1:/data/db

  mongo-express:
    image: mongo-express
    networks:
      mongo-network:
        ipv4_address: 172.28.11.3
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

